# Generated by Django 4.2.1 on 2024-02-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('pincode', models.IntegerField(max_length=10)),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('note', models.TextField(max_length=50)),
            ],
        ),
    ]
