# Generated by Django 4.2.1 on 2024-02-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
