# Generated by Django 4.2.1 on 2024-02-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_reservation_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(max_length=75),
        ),
    ]
