# Generated by Django 4.2.1 on 2024-03-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_reservation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='repeatpassword',
        ),
    ]
