# Generated by Django 4.2.1 on 2024-03-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_add_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_product',
        ),
    ]
