# Generated by Django 4.2.1 on 2024-03-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_add_to_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
