# Generated by Django 4.2.1 on 2024-03-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_add_to_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='note',
        ),
    ]
