# Generated by Django 4.2.1 on 2024-03-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_checkout_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkout',
            new_name='Billing_address',
        ),
    ]
