# Generated by Django 4.2.1 on 2024-03-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_address',
            name='user_id',
        ),
    ]
