# Generated by Django 4.2.1 on 2024-03-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_billing_address_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing_address',
        ),
    ]
