# Generated by Django 4.2.1 on 2024-03-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_billing_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_address',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='billing_address',
            name='list',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
