# Generated by Django 4.2.1 on 2024-03-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_rename_user_billing_address_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing_address',
        ),
    ]
