# Generated by Django 4.2.1 on 2024-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='notes',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
