# Generated by Django 4.2.1 on 2024-03-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_billing_address_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_address',
            old_name='notes',
            new_name='note',
        ),
    ]
